### ISSUE TITLE
Write unit tests for GameRunner class using chai

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#60]
Tests can be added here: https://github.com/JSJitsu/ai-battle-website/blob/master/gamerunner/test/index.js

Write unit tests to improve code coverage of the GameRunner class, located in _gamerunner/game_logic_, so we have some level of confidence that pushing to production will not unintentionally prevent games from running.

**Comment by adrichey** [comment]
I will get some tests written for you today. I will start in on this now. 😄

**Comment by adrichey** [comment]
Just opened the following pull request: https://github.com/JSJitsu/ai-battle-website/pull/66

It is failing the Travis CI build step, due to the config.js file not being copied over from config-template.js. That will need to be updated if this pull request is merged in. If this looks good I will continue to write tests when I have more time next week.

**Comment by Asuza** [comment]
Thanks! It looks good so far. I'm looking into fixing the build, and will let you know when it's working.

**Comment by Asuza** [comment]
@adrichey, if you pull in _master_, the build will be fixed. If you want to add tests that require a database, please let me know and I'll work on getting that into the build.

**Comment by adrichey** [comment]
Cool, it looks like your Travis changes got us through the build. I will try writing more tests throughout the week.

**Comment by Asuza** [comment]
Thanks for getting this started, @adrichey! Finally got it merged somewhere.
Fixed via #66.
